const commons = (name) => `https://commons.wikimedia.org/wiki/File:${name}`;
export const STORIES = [
  {
    id: "shore-photo",
    label: "The shore album",
    title: "Boats between journeys",
    mlTitle: "കടൽത്തീരത്തെ വള്ളങ്ങൾ",
    x: -74,
    z: 12,
    frame: { x: -76, z: 16 },
    place: "Kadal fishing shore",
    location: "Kerala coast",
    date: "12 October 2019",
    image: "shore",
    author: "Josephgeorge23",
    license: "4.0",
    source: commons("Fishing_boats_in_Kerala,_India.jpg"),
    alt: "Fishing boats resting together along a Kerala beach.",
    en: "This real photograph records fishing boats on a Kerala beach in 2019. Look at the different hulls and the space between the boats. In Kadal, Sasi's journey is a fictional interpretation, with simplified work and weather.",
    ml: "2019-ൽ കേരളത്തിലെ ഒരു കടൽത്തീരത്ത് എടുത്ത ചിത്രമാണിത്. വള്ളങ്ങളുടെ രൂപങ്ങൾ ശ്രദ്ധിക്കൂ. കളിയിലെ ശശിയും അദ്ദേഹത്തിന്റെ യാത്രയും സാങ്കൽപ്പികമാണ്.",
    notice:
      "Back in the village, notice what changes at the shore while Sasi is away.",
  },
  {
    id: "coir-photo",
    label: "The coir photograph",
    title: "A coconut becomes a thread",
    mlTitle: "തൊണ്ടിൽ നിന്ന് കയറിലേക്ക്",
    x: 62,
    z: -44,
    frame: { x: 62, z: -49 },
    place: "Radha's Coir Yard",
    location: "Kollam",
    date: "28 November 2005",
    image: "coir",
    author: "albert (The Netherlands)",
    license: "2.0",
    source: commons(
      "Women_at_work_in_a_small_scale_coir_spinning_unit_at_kollam.jpg",
    ),
    factSource: "https://coirboard.gov.in/?page_id=60",
    alt: "Two women at work in a coir-spinning unit in Kollam.",
    en: "Coir is fibre from the coconut's outer husk. It is used in rope, mats and other products. This photograph shows coir-spinning work in Kollam. The material connects coconut trees with the work you see in Radha's fictional yard.",
    ml: "തേങ്ങയുടെ തൊണ്ടിൽ നിന്നാണ് ചകിരിനാര് ലഭിക്കുന്നത്. കയറും പായയും ഉണ്ടാക്കാൻ ഇത് ഉപയോഗിക്കുന്നു. കൊല്ലത്തെ കയർനിർമാണത്തിന്റെ ഒരു ചിത്രമാണിത്.",
    notice:
      "Look again at the fibre, the finished rope and the coconut palms around the yard.",
  },
  {
    id: "tea-photo",
    label: "Leela's photo wall",
    title: "A pause at Thattekkaad",
    mlTitle: "തട്ടേക്കാട്ടെ ചായക്കട",
    x: -10,
    z: 30,
    frame: { x: -11, z: 25 },
    place: "Leela's Chaya",
    location: "Thattekkaad · Ernakulam",
    date: "23 December 2016",
    image: "tea",
    author: "Shagil Kannur",
    license: "4.0",
    source: commons("A_village_tea_shop_in_Kerala.jpg"),
    alt: "A village tea shop at Thattekkaad, photographed in 2016.",
    en: "The photographer identifies this as a tea shop at Thattekkaad, photographed in 2016. Spend a moment looking at its setting and everyday details. Leela's shop is fictional; this is a real place to compare with it, not a photograph of Kadal.",
    ml: "2016-ൽ തട്ടേക്കാട്ടെ ഒരു ചായക്കടയിൽ എടുത്ത ചിത്രമാണിത്. കടയും ചുറ്റുപാടും ശ്രദ്ധിക്കൂ. കളിയിലെ ലീലയുടെ കട സാങ്കൽപ്പികമാണ്.",
    notice:
      "Step back outside and listen to the conversations around Leela's veranda.",
  },
  {
    id: "thumba-story",
    label: "The coastal science board",
    title: "A coast looking skyward",
    mlTitle: "ആകാശത്തേക്ക് നോക്കിയ തീരം",
    x: -58,
    z: 620,
    frame: { x: -58, z: 617 },
    place: "Southern coastal path",
    location: "Thumba · Thiruvananthapuram",
    date: "21 November 1963",
    source: "https://www.isro.gov.in/soundingRockets.html",
    sourceLabel: "ISRO: sounding rockets",
    en: "On 21 November 1963, the first sounding rocket from Thumba, near Thiruvananthapuram, rose into the sky. ISRO identifies this launch as the beginning of the Indian Space Programme. Sounding rockets carry instruments to study the upper atmosphere. This coastal board connects the sea beside you with another way of looking beyond the horizon.",
    ml: "1963 നവംബർ 21-ന് തിരുവനന്തപുരത്തിനടുത്തുള്ള തുമ്പയിൽ നിന്ന് ആദ്യ സൗണ്ടിങ് റോക്കറ്റ് വിക്ഷേപിച്ചു. ഇന്ത്യൻ ബഹിരാകാശ പദ്ധതിയുടെ തുടക്കമായി ഐഎസ്ആർഒ ഈ വിക്ഷേപണത്തെ അടയാളപ്പെടുത്തുന്നു. അന്തരീക്ഷത്തിന്റെ ഉയർന്ന ഭാഗങ്ങൾ പഠിക്കാൻ ഇത്തരം റോക്കറ്റുകൾ ഉപയോഗിക്കുന്നു.",
    notice:
      "Look from the sea to the sky. This path is fictional; it is not the Thumba launch site.",
  },
  {
    id: "chemmeen-story",
    label: "The coastal film-club board",
    title: "A fishing coast on screen",
    mlTitle: "തിരശ്ശീലയിലെ കടൽത്തീരം",
    x: -67,
    z: 23,
    frame: { x: -67, z: 20 },
    place: "Kadal shore film board",
    location: "Kerala · Malayalam cinema",
    date: "1965",
    source: "https://www.keralaheritage.org/cinema/cultural",
    sourceLabel: "Kerala Heritage: cinema history",
    factSource:
      "https://nfai.nfdcindia.com/pdf/Digitized%20and%20Restored%20Films_16-12-2016.pdf",
    factSourceLabel: "National Film Archive of India: film catalogue",
    en: "Chemmeen (1965), directed by Ramu Kariat, adapts Thakazhi Sivasankara Pillai's novel. Kerala Heritage records it as the first South Indian film to receive the President's Golden Lotus for best Indian film. Its coastal world offers one artistic portrayal of a fishing community. A film tells a particular story; the lives along a real coast are many.",
    ml: "തകഴി ശിവശങ്കരപ്പിള്ളയുടെ നോവലിനെ ആസ്പദമാക്കി രാമു കാര്യാട്ട് സംവിധാനം ചെയ്ത ചിത്രമാണ് ചെമ്മീൻ (1965). മികച്ച ഇന്ത്യൻ ചിത്രത്തിനുള്ള രാഷ്ട്രപതിയുടെ സുവർണ കമലം നേടിയ ആദ്യ ദക്ഷിണേന്ത്യൻ ചിത്രമായി കേരള ഹെറിറ്റേജ് ഇതിനെ രേഖപ്പെടുത്തുന്നു. തീരദേശജീവിതത്തിന്റെ ഒരു കലാവിഷ്കാരമാണിത്.",
    notice:
      "Watch the boats and work along the shore again. What would you choose to put in a scene of your own?",
  },
  {
    id: "silent-valley-story",
    label: "The forest reading board",
    title: "A forest people stood up for",
    mlTitle: "കാടിനായി ഒന്നിച്ചവർ",
    x: 456,
    z: -477,
    frame: { x: 456, z: -480 },
    place: "High-range forest approach",
    location: "Silent Valley · Kerala",
    date: "A conservation story",
    source: "https://forest.kerala.gov.in/en/national-parks/",
    sourceLabel: "Kerala Forest Department: national parks",
    en: "Silent Valley protects tropical rainforest in Kerala's Nilgiri hills. In the 1970s, the Save Silent Valley movement opposed a proposed hydroelectric project. The Kerala Forest Department links that campaign with the protection of the forest and the national park's establishment in 1984. A landscape can hold the memory of people choosing to protect it.",
    ml: "കേരളത്തിലെ നീലഗിരി മലനിരകളിലുള്ള ഉഷ്ണമേഖലാ മഴക്കാടാണ് സൈലന്റ് വാലി. 1970-കളിൽ നിർദിഷ്ട ജലവൈദ്യുത പദ്ധതിക്കെതിരെ സൈലന്റ് വാലി സംരക്ഷണ പ്രസ്ഥാനം ഉയർന്നു. വനസംരക്ഷണത്തിനും 1984-ലെ ദേശീയോദ്യാന രൂപീകരണത്തിനും വഴിയൊരുക്കിയ പ്രസ്ഥാനത്തെക്കുറിച്ച് കേരള വനം വകുപ്പ് വിവരിക്കുന്നു.",
    notice:
      "Pause and listen along the forest edge. This fictional forest is a connection to Silent Valley, not a recreation of the park.",
  },
];
export const storyById = (id) => STORIES.find((s) => s.id === id);
export const storyImage = (story, small = false) =>
  story.image ? `/stories/${story.image}${small ? "-small" : ""}.jpg` : null;
